version: "3.9"
services:
   nginx:
     build: ./nginx/
     ports:
       - 80:80
  
     volumes:
         - /home/rrr/codes/:/var/www/html/
   php:
     build: ./php_code/
     expose:
       - 9000
     volumes:
        - /home/rrr/codes/:/var/www/html/
#
#   db:    
#      image: mariadb  
#      volumes: 
#        -    mysql-data:/var/lib/mysql
#      environment:  
#       MYSQL_ROOT_PASSWORD: mariadb
#       MYSQL_DATABASE: ecomdb 


volumes:
    mysql-data: